### ISSUE TITLE
Lesson01/ Exercise04/ ProductsOfNos.java Exception 

### ISSUE THREAD

**Issue by chikega** [TrainingByPackt/Java-Fundamentals#17]
Using Java 8, the current code throws an exception:  
`Enter the first number
Exception in thread "main" java.lang.NullPointerException
	at Main.main(Main.java:7)`

The code is missing 'throws IOException', the same exception is thrown when added to code.

Using Java 17, the exception reads as follows:  
`
Enter the first number: Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.io.Console.readLine()" because the return value of "java.lang.System.console()" is null
	at Main.main(Main.java:11)
`

**Comment by visola** [comment]
This `NullPointerException` happens if for some reason the place where you running the class from doesn't have a `console` available. According [to the Javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#console--), it can happen but it is not clear where, when or how it would.
Where did you run this code from?
Using Java 8 Amazon's Correto JVM, I see no issues:
```
 Java-Fundamentals/Lesson01/Exercise04 $ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment Corretto-8.282.08.1 (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM Corretto-8.282.08.1 (build 25.282-b08, mixed mode)

 Java-Fundamentals/Lesson01/Exercise04 $ javac ProductOfNos.java; java ProductOfNos
Enter the first number
10
Enter the Second number
10
The product of the two numbers is 100%
```

Also, it throws a `NullPointerException`, adding the `throws IOException` in there would not fix this issue. Sorry, I merged that too fast thinking it was a compilation issue.

**Comment by chikega** [comment]
I've tested this on three computers, one of which is a new computer that has never had a JDK installed. I downloaded Amazon Corretto Java 8.  A fresh copy of IntelliJ for the new computer. Started new projects. Copied and inserted the code into the IntelliJ IDEAs And I'm receiving the same exceptions on all computers, even the new one: 
```
"C:\Program Files\Amazon Corretto\jdk1.8.0_332\jre\bin\java.exe" ... 
Enter the first number
Exception in thread "main" java.lang.NullPointerException
	at Main.main(Main.java:7)
```
BUT, when I typed the code into Replit.com, it works. It uses Java 17.0.1. So I'm left baffled.

**Comment by visola** [comment]
Did you type a number when it asked you to?
I just noticed that the `NullPointerException` could also come from no input coming from the console and trying to parse that into a number.
Did the console waited for you to type something or it just explodes immediately?

**Comment by chikega** [comment]
Just exploded immediately. No input was ever entered.

**Comment by chikega** [comment]
I installed IntelliJ on Linux Mint (VM) with default open jdk 11.0.9.1 2020-11-04 and it threw the same exception. So I decided to get back to the basics by going to the terminal. Compiling the code with javac and running with java in a terminal worked. It may be an IntelliJ issue and I will bring the matter to their attention. Thank you for your help.

**Comment by visola** [comment]
It could be the way the project is setup in Gradle. My IntelliJ wasn't able to recognize the code to run. This project does not follow standard Gradle folder structure. The files were just put there as a reference for the book.

**Comment by chikega** [comment]
My IntelliJ defaults to its own build system called 'IntelliJ', but Maven and Gradle are offered as alternatives. I did more testing on various platforms, different IDE's  (Eclipse, JGrasp..), different builds (Ant, Maven, Gradle) and all seem to throw the same exceptions. To be honest, this code is not something you see routinely in beginner Java textbooks as the Scanner object has taken precedence, although I like the syntax very much which reminds me of Pascal/Nim or C#. 

`var num1 = Int32.Parse(System.Console.ReadlLine());    //C#`

But, after doing more research, it appears that  `System.Console()` may be the 'culprit'. From [Oracle docs:](https://docs.oracle.com/javase/tutorial/essential/io/cl.html)
> "Before a program can use the Console, it must attempt to retrieve the Console object by invoking `System.console()`. If the Console object is available, this method returns it. If `System.console()` returns `NULL`, then Console operations are not permitted, either because the OS doesn't support them or because the program was launched in a noninteractive environment."

From [StackOverflow](https://stackoverflow.com/questions/34555185/system-console-nullpointerexception): 

`How do you launch your application? Whether a virtual machine has a console is dependent upon the underlying platform and also upon the manner in which the virtual machine is invoked. If the virtual machine is started from an interactive command line without redirecting the standard input and output streams then its console will exist and will typically be connected to the keyboard and display from which the virtual machine was launched. If the virtual machine is started automatically, for example by a background job scheduler, then it will typically not have a console.`

So perhaps this may be the reason the code runs from a terminal (or [Replit](https://replit.com)) and not the IDE's. :)

**Comment by visola** [comment]
This is really helpful. A lot more details and it clarifies a lot.
Thank you for spending time on this.

**Comment by chikega** [comment]
Some additional info from [IntelliJ's YouTrack issue](https://youtrack.jetbrains.com/issue/IDEABKL-5949/System.console()-returns-null)s.
